services:
  flask-dev:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: test/pytorchflask
    container_name: flask-torch-app
    ports: 
      - "5000:5000"
      - "5678:5678"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app", "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]
