services:
  geotiff:
    build:
      context: .
      # target: dev
      dockerfile: Dockerfile
    image: geotiff
    container_name: geotiff
    ports: 
      - "5000:5000"
      - "5678:5678"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app", "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]

  geotiff-deploy:
    build:
      context: .
      # target: prod
      dockerfile: Dockerfile
    image: geotiff_depl
    container_name: geotiff_depl
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./images/:/app/images/
    ports: 
      - "5000:5000"
    entrypoint: ["python", "app.py"]