services:
  flask-debug:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    image: flaskdev
    container_name: flaskdev
    ports: 
      - "5000:5000"
      - "5678:5678"
    environment:
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app", "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]

  flask-deploy:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    image: bitouflask
    container_name: bitouflask
    ports: 
      - "5000:5000"
    entrypoint: ["python", "app.py"]
  
  flask-gpu:
    build:
      context: .
      dockerfile: Dockerfile_GPU
    image: bitou_gpu
    container_name: bitou_gpu
    ports:
      - "5000:5000"
    entrypoint: ["python", "app.py"]